//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityTransport_DLL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SoftlandEntities : DbContext
    {
        public SoftlandEntities()
            : base("name=SoftlandEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_Transporte_Factura_Obtener_Result> SP_Transporte_Factura_Obtener(string pNunFactura)
        {
            var pNunFacturaParameter = pNunFactura != null ?
                new ObjectParameter("pNunFactura", pNunFactura) :
                new ObjectParameter("pNunFactura", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Transporte_Factura_Obtener_Result>("SP_Transporte_Factura_Obtener", pNunFacturaParameter);
        }
    }
}
